# .github/workflows/generate-api-docs.yml
name: Generate and Commit API Docs

# Controls when the action will run.
on:
  # Triggers the workflow at 00:00 UTC every day.
  schedule:
    - cron: '0 0 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "generate-docs"
  generate-docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Sets up Python environment for the make command
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Use a recent Python 3 version

      # 3. Runs the make command to install dependencies and generate the docs
      - name: Generate API Documentation
        run: make api-docs
        
      # 4. Commits the changed files in the 'api-docs' directory
      - name: Commit Documentation Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(api): Auto-generate API documentation"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "GitHub Actions Bot <github-actions[bot]@users.noreply.github.com>"
          # The pattern of files to commit. This will commit the entire api-docs directory.
          file_pattern: "api-docs/."
